kind: pipeline
name: default
type: docker


workspace:
  base: /go
  path: src/github.com/oliver006/elasticsearch-gmail


services:
  - name: es
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.6.1
    environment:
      http.port: "9200"
      discovery.type: "single-node"
    ports:
      - 9200


steps:
  - name: tests
    image: "python:3.7"
    pull: always
    commands:
      - pip3 install -r requirements.txt
      - sleep 30
      - curl -s http://es:9200
      - "python3 es_test_data.py -es_url=http://es:9200"
    when:
      event:
        - pull_request
        - push
