kind: pipeline
name: default
type: docker


workspace:
  base: /go
  path: src/github.com/oliver006/elasticsearch-gmail


services:
  - name: es
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.6.1
    environment:
      http.port: "9200"
      discovery.type: "single-node"
    ports:
      - 9200


steps:
  - name: tests
    image: "python:3.7"
    pull: always
    commands:
      - pip3 install -r requirements.txt
      - sleep 30
      - curl -s http://es:9200
      - "python3 es_test_data.py -es_url=http://es:9200"
    when:
      event:
        - pull_request
        - push


  - name: test-docker-build
    image: plugins/docker
    settings:
      tags: "test"
      dockerfile: Dockerfile
      repo: oliver006/es-test-data
      dry_run: true
      build_args:
        - 'TAG=test'
        - 'SHA1=${DRONE_COMMIT_SHA}'
        - 'GOARCH=amd64'
      username:
        from_secret: docker_user
      password:
        from_secret: docker_pass
    when:
      event:
        - push
        - pull_request
        - tag


  - name: release-docker-image
    image: plugins/docker
    settings:
      tags: "latest"
      dockerfile: Dockerfile
      repo: oliver006/es-test-data
      build_args:
        - 'TAG=${DRONE_TAG}'
        - 'SHA1=${DRONE_COMMIT_SHA}'
        - 'GOARCH=amd64'
      username:
        from_secret: docker_user
      password:
        from_secret: docker_pass
    when:
      event:
        - push
      branch:
        - master


